name: streamlit4
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.3
  - chembl_structure_pipeline=1.0.0
  - rdkit=2022.03.5
  - pip:
    - altair==4.2.0
    - asttokens==2.0.8
    - attrs==22.1.0
    - backcall==0.2.0
    - blinker==1.5
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - click==8.1.3
    - colorama==0.4.5
    - commonmark==0.9.1
    - decorator==5.1.1
    - entrypoints==0.4
    - executing==1.1.1
    - gitdb==4.0.9
    - gitpython==3.1.29
    - idna==3.4
    - imbalanced-learn==0.9.1
    - imblearn==0.0
    - importlib-metadata==5.0.0
    - ipython==8.5.0
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==4.16.0
    - lightgbm==3.3.2
    - markupsafe==2.1.1
    - matplotlib-inline==0.1.6
    - parso==0.8.3
    - pickleshare==0.7.5
    - plotly==5.10.0
    - prompt-toolkit==3.0.31
    - protobuf==3.20.3
    - pure-eval==0.2.2
    - pyaml==21.10.1
    - pyarrow==9.0.0
    - pydeck==0.8.0b4
    - pygments==2.13.0
    - pympler==1.0.1
    - pyrsistent==0.18.1
    - python-decouple==3.6
    - pytz-deprecation-shim==0.1.0.post0
    - pyyaml==6.0
    - requests==2.28.1
    - rich==12.6.0
    - scikit-learn==1.1.2
    - scikit-optimize==0.9.0
    - scipy==1.9.3
    - seaborn==0.12.0
    - semver==2.13.0
    - smmap==5.0.0
    - stack-data==0.5.1
    - streamlit==1.13.0
    - streamlit-aggrid==0.3.3
    - streamlit-on-hover-tabs==1.0.1
    - tenacity==8.1.0
    - threadpoolctl==3.1.0
    - toml==0.10.2
    - toolz==0.12.0
    - tornado==6.2
    - traitlets==5.5.0
    - typing-extensions==4.4.0
    - tzdata==2022.5
    - tzlocal==4.2
    - urllib3==1.26.12
    - validators==0.20.0
    - watchdog==2.1.9
    - wcwidth==0.2.5
    - zipp==3.9.0


